CHANGELOG.md
lib/gruf/configuration.rb
lib/gruf/service.rb
spec/gruf/service_spec.rb

Sending along an uncaught exception message by default can be considered insecure. This can leak server information to clients of the service unintentionally. 
This PR will set the error_message for an uncaught exception and allow a user to both modify the error message as well as enable sending the exception message if that is intended behavior.
Rspec tests have been added.

Update configuration and global exception handler to not pass e.message.

---

lib/gruf/configuration.rb
lib/gruf/server.rb
spec/gruf/server_spec.rb

Ability to configure `GRPC::RpcServer` (e.g. `pool_size`) was missing (http://www.rubydoc.info/gems/grpc/GRPC/RpcServer#initialize-instance_method). 
Specs and running `bundle exec gruf` with and without additional config.

Allow GRPC::RpcServer configuration

---

CHANGELOG.md
README.md
spec/gruf/interceptors/active_record/connection_reset_spec.rb
spec/support/rails.rb

Fixes #30 - which is caused by `::ActiveRecord::Base.clear_active_connections!` not properly clearing connections during the hook. This PR ensures that the `clear_active_connections!` call is made, and also properly tries to re-establish the connection on each new call.
Also fixes #29 in README.
----
@pedelman

Fix issue with AR connection pooling in Rails 5

---

lib/gruf/server.rb
spec/gruf/server_spec.rb

Fixes #32 
Spec + extensive testing in production

Rescue signal exception

---

bin/gruf

Can not use gruf in a non-rails application.
https://github.com/bigcommerce/gruf/issues/34
Tested locally in irb.
```bash
xinchen.shen@xinchen ~/SandBox/gruf (fix-LoadError) $ ./bin/console
>> require 'rails' rescue nil
LoadError: cannot load such file -- rails
from (irb):1:in `require'
from (irb):1
from ./bin/console:26:in `<main>'
>> begin
?>   require 'rails'
>> rescue LoadError
>>   nil
>> end
=> nil
```

Fix LoadError for non-rails applications

---

CHANGELOG.md
README.md
lib/gruf/interceptors/registry.rb
lib/gruf/server.rb
spec/gruf/interceptors/registry_spec.rb
spec/gruf/server_spec.rb

* Add ability to list, clear, insert before, and insert after to a server's interceptor
registry
* Ensure interceptors and services cannot be adjusted on the server after it starts to 
prevent threading issues and other unwanted behavior
rspec, `spec/demo_server`, and other testing.

Interceptor registry improvements

---

README.md
lib/gruf/interceptors/instrumentation/request_logging/interceptor.rb
spec/gruf/interceptors/instrumentation/request_logging/interceptor_spec.rb

When you use e.g. healthchecks logs can get really crouded with those.
With spec

ignore_methods option for RequestLogging interceptor

---

CHANGELOG.md
lib/gruf/interceptors/instrumentation/request_logging/interceptor.rb
spec/gruf/interceptors/instrumentation/request_logging/interceptor_spec.rb

Fixes issue #49, returns as INFO for InvalidArguments
See spec. Assume we return as INFO if we raise InvalidArgument exception.

fix(platform): GRUF-49 Interpret InvalidArguments as info, not errors.

---

README.md

First of all - We have started using gruf recently in one project at work. It works great, thanks for this gem.
However, when I wrote my own grpc controller with gruf, it took me a while to understand how to test it. I think it would be beneficial to add such info to README.
Hope that what I have wrote make sense.
It's just readme ;)

README: Add section about testing controllers

---

README.md

I corrected two code examples in the README which were wrong.
The first one is about the `client_options`, this parameter must be a hash, not an array.
The second one is for the SSL certificate, this parameter must be provided inside the `options` hash.
It is just the readme file!
I hope this helps!

Updated README, two code examples were wrong

---

CHANGELOG.md
lib/gruf/configuration.rb
lib/gruf/error.rb
lib/gruf/errors/debug_info.rb
spec/gruf/error_spec.rb

* The gRPC C library has a default max size on trailing metadata of 8kb. Update the Error class to consider this when attaching metadata to the gRPC call. If the overall size of the metadata, including metadata added by the application, and the error payload added by the error serializer, is in danger of exceeding that limit, log the error and replace the wire error with a new one indicating metadata overflow.
* Truncate stack trace attached to error payload to ten lines to reduce risk of overflow.
* gRPC server app with an endpoint that calls `fail!(:internal, :unknown, SecureRandom.hex(9000))`
* Call it with a client that logs the response
Server side:
```
I, [2018-08-16T18:48:43.173244 #2735]  INFO -- : deadline is 1969-12-31 15:59:59 -0800; (now=2018-08-16 18:48:43 -0700)
I, …
```

PEN-925: Handle overflow of metadata

---

lib/gruf/interceptors/instrumentation/request_logging/interceptor.rb

```
require 'grpc'
require 'peatio/smaug/v2/account_pb'
module Peatio
module Smaug
module V2
module Accounts
class Service
include GRPC::GenericService
self.marshal_class_method = :encode
self.unmarshal_class_method = :decode
self.service_name = 'peatio.smaug.v2.Accounts'
rpc :List, ListAccountsRequest, stream(Account)
rpc :DoTransaction, stream(UpdateAccountRequest), stream(Account)
end
Stub = Service.rpc_stub_class
end
end
end
end
```
The request and response of service are both stream type
It is a bidi_streamer request
https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/generic/rpc_desc.rb#L187
```
```
Passed in my case

skip params log for bidi_streamer request

---

CHANGELOG.md
README.md
gruf.gemspec
lib/gruf.rb
lib/gruf/configuration.rb
lib/gruf/synchronized_client.rb
spec/gruf/synchronized_client_spec.rb
spec/support/helpers.rb

To help with cases where you might have spikes of traffic to a given endpoint (so-called thundering herds), SynchronizedClient puts locks around Client calls to a given endpoint with the same params.
* Unit tests
* A server endpoint that uses Gruf::Client to call out to another service was updated to use Gruf::SynchronizedClient and a test client was used to generate load against it. I observed the debug logs and saw the expected behavior.

Add SynchronizedClient to mitigate thundering herds

---

CHANGELOG.md
lib/gruf/client.rb
lib/gruf/controllers/base.rb
spec/gruf/client_spec.rb
spec/gruf/controllers/base_spec.rb

When `timeout` is passed as a client option to `Gruf::Client`, we want to ensure it is always an int, as this is now enforced in the core gRPC library. This fixes an issue where if someone were to pass `timeout: '300'` it would cause a downstream gRPC TimeConst error.
Also, added a new `bound_service` class method to Gruf Controllers, that allows you to introspect the service being bound to the delegated controller. Given this:
```ruby
class MyRpcController < Gruf::Controllers::Base
bind MyGrpcService
end
```
Now you can do:
```
MyRpcController.bound_service # => MyGrpcService
```
This is useful for spec testing.
----
@bigcommerce/platform-engineering @mattolson @hx @billthompson @pedelman

Cast timeout client opt to int; attach bound service name to controller class

---

.travis.yml
CHANGELOG.md
Gemfile
lib/gruf/interceptors/instrumentation/request_logging/interceptor.rb
spec/gruf/interceptors/instrumentation/request_logging/interceptor_spec.rb

Reduces defaults for OK/validation-level errors in the request log handler to `debug`, which prevents log stampeding in environments receiving very high traffic.
Also bumps rubocop to get rid of a warning when running.
`rspec` and through performance/regression testing.
----
@zackangelo @pedelman @mattolson @junedkazi @chrisboulton

Log ok/validation responses at DEBUG levels to prevent log stampeding

---

lib/gruf/controllers/base.rb

A simple abstraction on send of Controllers::Base. I want to include `AbstractController::Callbacks` of Rails on my controller and this makes easy to do it.
Why `process_action`? Because https://github.com/rails/rails/blob/v3.1.0/actionpack/lib/abstract_controller/base.rb#L166
and https://github.com/rails/rails/blob/v3.1.0/actionpack/lib/abstract_controller/callbacks.rb#L16
It does not break the actual behavior. Here what I want to do:
```ruby
class MyController < Gruf::Controllers::Base
include AbstractController::Callbacks
attr_accessor :performed
def performed?
@performed || false
end
def action_name
request&.method_key.to_s
end
before_action :run_before
after_action :run_after
def my_method
puts 'my_method is running'
end
def run_before
puts 'this will run before my_method'
end
def …
```

Abstract the controller :send making easy to include Rails components

---

lib/gruf.rb
lib/gruf/configuration.rb
lib/gruf/integrations/rails/railtie.rb

The `Configuration::reset` didn't get right configs of Rails(`Rails.logger`, `Rails.root`), we should put the `reset` in Rails initialization hook.
Before the commit:
```ruby
rails c # => Loading development environment (Rails 5.1.6)
Gruf.logger # => ...@dev=#<IO:<STDOUT>
Gruf.grpc_logger # => ...@dev=#<IO:<STDOUT>
Gruf.root_path # => ""
Gruf.controllers_path # => "app/rpc"
```
After the commit:
```ruby
rails c # => Loading development environment (Rails 5.1.6)
Gruf.logger # => ...@dev=#<File:/Users/pinewong/works/warehouse/log/development.log>
Gruf.grpc_logger # => ...@dev=#<File:/Users/pinewong/works/warehouse/log/development.log>
Gruf.root_path # => "/Users/pinewong/works/warehouse"
Gruf.controllers_path # => "/Users/pinewong/works/warehouse/app/rpc"
```

Fix the default config in Rails environment

---

lib/gruf/cli/executor.rb

The `Logger` in module `Gruf` will explain to `Gruf::Logger`, this is not expected.
When you set `Gruf.logger` to `nil` manually, this will occur.

Fix Logger in executor

---

CHANGELOG.md
README.md
lib/gruf/cli/executor.rb
lib/gruf/configuration.rb
lib/gruf/hooks/base.rb
lib/gruf/hooks/executor.rb
lib/gruf/hooks/registry.rb
spec/demo_server
spec/gruf/cli/executor_spec.rb
spec/gruf/hooks/executor_spec.rb
spec/gruf/hooks/registry_spec.rb
spec/support/hooks.rb

Adds hook support for executing code paths before a server is started, and after a server stops, as well as a generic hook registry and base class. This allows for execution of code outside of the normal request chain, which can be used to provide server instrumentation, process monitoring, and more.
```ruby
class MyHook < Gruf::Hooks::Base
def before_server_start(server:)
end
def after_server_stop(server:)
end
end
Gruf.configure do |c|
c.hooks.use(MyHook, option_foo: 'value 123')
end
```
`spec/demo_server` has a successful hook implementation. Also ran against a live server and tested proper startup/shutdown, and ensured memory was released properly.
----
@bigcommerce/oss-maintainers @bigcommerce/ruby @bigcommerce/platform-engineering

Add hook support for executing code paths before a server is started and after a server stops

---

CHANGELOG.md
lib/gruf/client.rb
lib/gruf/configuration.rb
spec/gruf/client_spec.rb

This PR resolves #85 by adding a new option (`channel_credentials`) to the `Gruf::Client` class and a corresponding default (`default_channel_credentials`) to the `Gruf::Configuration` module.
These changes were implemented in response to @splittingred's [feedback on #85](https://github.com/bigcommerce/gruf/issues/85#issuecomment-560463847):
> I think allowing passing a `GRPC::Core::ChannelCredentials` is reasonable, as long as we maintain backwards support for the current implementation.
**Note:** I didn't include a check that `channel_credentials` are an instance of `GRPC::Core::ChannelCredentials`, so the assumption is that end users pass in the appropriate value. Happy to add that sort of check, though, if y'all think it'd be helpful.
Thanks for considering this addition to Gruf!
When …

New Feature: pass GRPC::Core::ChannelCredentials when instantiating Gruf::Client

---

.rubocop.yml
CHANGELOG.md
lib/gruf/interceptors/instrumentation/request_logging/formatters/base.rb
lib/gruf/interceptors/instrumentation/request_logging/formatters/logstash.rb
lib/gruf/interceptors/instrumentation/request_logging/formatters/plain.rb
lib/gruf/interceptors/instrumentation/request_logging/interceptor.rb
spec/demo_server
spec/gruf/interceptors/instrumentation/request_logging/formatters/base_spec.rb
spec/gruf/interceptors/instrumentation/request_logging/formatters/logstash_spec.rb
spec/gruf/interceptors/instrumentation/request_logging/formatters/plain_spec.rb
spec/gruf/interceptors/instrumentation/request_logging/interceptor_spec.rb

Addresses #92 by passing the controller request and response into request logging formatters.
Specs, and starting demo server, issuing requests. Ensure everything works properly.
----
@bigcommerce/oss-maintainers @zinosama @bigcommerce/ruby

Pass the controller request and response into the request logging formatters [#92]

---

gruf.gemspec

Loosens rake dependency to handle CVE alert.
CircleCI.
----
@bigcommerce/oss-maintainers @bigcommerce/ruby @bigcommerce/platform-engineering

Bump rake to a looser dependency to handle CVE-2020-8130

---

CHANGELOG.md
lib/gruf/cli/executor.rb
spec/gruf/cli/executor_spec.rb

Due to the way the configuration elements are loaded in Gruf, the CLI executor is not respecting --suppress-default-interceptors. This fixes that issue, and adds tests for it (and all other CLI args).
`bin/gruf --suppress-default-interceptors`, prying in to ensure success, and also through rspec tests.
----
@bigcommerce/oss-maintainers @bigcommerce/ruby @bigcommerce/platform-engineering @alikinir

Fix issue where CLI --suppress-default-interceptors was ignored

---

Rakefile
spec/demo_server
spec/pb/thing_controller.rb

Improves the demo server test code and Rakefile clients to more clearly show how to do streamed request/responses and bidi streams.
`spec/demo_server` in one shell, then the various rake tasks:
- `rake gruf:demo:get_thing` - unary
- `rake gruf:demo:get_things` - server streamer
- `rake gruf:demo:create_things` - client streamer
- `rake gruf:demo:create_things_in_stream` - bidi
----
@bigcommerce/oss-maintainers @bigcommerce/ruby @bigcommerce/platform-engineering

Improve demo server test code, more clearly show how to stream

---

lib/gruf/client/error.rb

According to official document https://github.com/grpc/grpc-go/blob/master/codes/codes.go, ResourceExhausted is one of the official gRPC error.
But ResourceExhausted error type is missing in client/errors.rb. Adding it in.
Include the new changes with a demo server, nothing should be affected.

ResourceExhausted is missing

---

CHANGELOG.md
gruf.gemspec

Explicitly declare the [json gem](https://rubygems.org/gems/json) dependency in the gemspec.
rspec, starting server, issuing requests, etc.
----
@bigcommerce/platform-engineering @bigcommerce/ruby @bigcommerce/oss-maintainers

Explicitly declare json dependency, fixes #108

---

.circleci/config.yml
CHANGELOG.md
Gemfile
README.md
gruf.gemspec
lib/gruf/client.rb
lib/gruf/controllers/request.rb
lib/gruf/hooks/executor.rb
lib/gruf/server.rb
script/e2e
script/test
spec/factories/controllers/request.rb

* Adds Ruby 2.7 support for gruf
* Explicitly declare development dependencies in gemspec as opposed to Gemfile
* Update methods passing hashes as keyword args to use double splats for 2.7 support. Note: some of the deprecation warnings still exist because of FactoryBot in tests, and in grpc core as well: https://github.com/grpc/grpc/pull/22915 - This specific deprecation warning is likely to be an issue for a _lot_ of gems, but is generally harmless.
Also adds two unit and end-to-end test scripts that can be used to verify functional operation of gruf beyond just the test suite.
See spec tests and e2e test script.
---
@bigcommerce/platform-engineering @bigcommerce/ruby @bigcommerce/oss-maintainers

Add Ruby 2.7 support

---

CHANGELOG.md
README.md
UPGRADING.md
lib/gruf/interceptors/instrumentation/request_logging/interceptor.rb
spec/gruf/interceptors/instrumentation/request_logging/interceptor_spec.rb

Terminology within gruf should not be racially insensitive or discriminatory. This moves gruf away from any racially discriminatory language, such as:
- `blacklist` becomes `blocklist`
- `master` will be changed to `main` after this PR is merged.
Note that systems using the blocklist functionality in the RequestLogging interceptor will need to adjust their reference to the parameter. We are preferring to have that be a forced changed rather than provide an upgrade path, to properly remove the biased language from the library in entirety.
rspec, running e2e tests.
----
@bigcommerce/platform-engineering @bigcommerce/ruby @bigcommerce/oss-maintainers

Change to racially neutral terminology across library

---

.circleci/config.yml
CHANGELOG.md
gruf.gemspec

[gRPC 1.35](https://github.com/grpc/grpc/releases/tag/v1.35.0) and [Protobuf 3.15](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0) (and newer versions of both) now support Ruby 3.0.  That means Gruf should now, hopefully, also be usable under Ruby 3.0.
The gemspec currently pins us to `~> 2.4`, which is equivalent to `>= 2.4, < 3.0` -- this PR does the following:
* loosen that requirement to `>= 2.4, < 3.1` to allow installing Gruf under Ruby 3.0
* ~~update the bundler development dependency.  This is maybe unrelated, except that bundler 2.0 was released January 2019-ish and I didn't want to have to install an older version locally to test this change :)~~ this broke CircleCI so I reverted it.
* The test suite passes.
* Smoke testing on ruby 3 locally with some simple …

Add support for installing Gruf under Ruby 3.0

---

CHANGELOG.md
lib/gruf/client.rb
spec/gruf/client_spec.rb

The current gruf implementation always casts `timeout` to an integer when passed. This prevents setting it to a float value, or to a TimeSpec (such as infinite) value, which is supported by gRPC core. This fixes that functionality and allows floats or TimeSpec objects to be passed, while still maintaining the gruf functionality to allow string timeouts to be set (and auto-cast to floats).
rspec + manually.
----
@bigcommerce/ruby @bigcommerce/oss-maintainers @alikinir

Allow for float/TimeSpec timeout values on clients

---

.circleci/config.yml

#144 Added CodeClimate, but runs it on every Ruby version. That causes conflict errors. This tweaks that to only run on Ruby 3.0 builds (as we are only statically analyzing code, not Ruby version interpretations of it).
This PR.

Only run code climate on Ruby 3.0 builds

---

CHANGELOG.md
lib/gruf/server.rb
spec/gruf/client_spec.rb
spec/gruf/server_spec.rb

Fixes issues introduced in ef139b7567f0387cf784ddc7e11f81d62eaea41f, fixes #147.
There seems to be a race condition when starting a `GRPC::RpcServer` in a thread, and attempting to use `server.wait_till_running` in the parent thread - `wait_till_running` never proceeds, even after the server is started. Us calling `server_thread.join` _after_ the `wait_till_running` call compounds this (likely the issue that the Thread never finishes executing and binding the connections before we proceed to a serving state).
This means that 2.13.0 is, in certain cases, starting servers that fail to establish serving connections properly.
This PR removes the wait_till_running call, and just joins on the Thread, allowing gRPC to handle the signals internally. While this means we will be updating the …

Fix issue with race condition in server starts where servers may fail to bind connections and never reach serving state

---

CHANGELOG.md
lib/gruf/configuration.rb

Sets the default client host to 0.0.0.0:9001, which is the same as the default server host (the match is useful for local testing).
This fixes #149, in where core grpc gem changes now break if the channel host is not explicitly specified.
rspec, manual

Set default client host to 0.0.0.0:9001 (same as default server host)

---

CHANGELOG.md
lib/gruf/server.rb
spec/gruf/server_spec.rb

In `Gruf::Server`, we thread out the starting of the server to allow for updating the process title and storing run state. `server`, which is the `GRPC::RpcServer`, is memoized on the `Gruf::Server` instance. However, in the current implementation, we were not protecting that memoization with a mutex to ensure thread-safety. This is especially problematic as the first time that the `server` method is called is inside the server starting thread (not the parent).
This PR adds such a mutex and ensures that the server variable is synchronized during access, so as to safely allow access to it and prevent the race condition where the server is unable to serve certain requests (like health checks).
rspec, manually:
```
18:34:26 grpc.1      | [DEBUG] {"message":"[GRPC::Ok] …
```

Fix issue where the server object hits thread contention in certain race conditions

---

.circleci/config.yml
CHANGELOG.md
lib/gruf/configuration.rb
spec/gruf/configuration_spec.rb

The `rubocop` job in CircleCI was not running, and instead was calling `bundle-audit`  a second time. This PR corrects that and fixes a found `rubocop` error with `Style/FetchEnvVar` in `Gruf::Configuration`.
Run `rubocop` and `rspec` locally.

Fix rubocop configuration and failing cop

---

CHANGELOG.md
lib/gruf/configuration.rb

Fix issue where GRPC_SERVER_POOL_KEEP_ALIVE and GRPC_SERVER_POLL_PERIOD when set via ENV are not cast to int. That would result in this error on shutdown:
```
grpc-1.46.3/src/ruby/lib/grpc/core/time_consts.rb:42:in `from_relative_time': Cannot make an absolute deadline from "1" (TypeError)
```
Manually by setting those values via ENV and confirming the fix.

Fix ENV casting issue with GRPC pool settings

---

CHANGELOG.md
lib/gruf.rb
lib/gruf/controllers/request.rb
spec/gruf/controllers/request_spec.rb
spec/gruf/interceptors/server_interceptor_spec.rb
spec/support/interceptors.rb

Adds a `context` attribute to `Gruf::Controllers::Request` that allows Server Interceptors to pass information between each other and down to gruf controllers. Fixes #163.
rspec, e2e test, console

Add `context` hash attribute to `Gruf::Controllers::Request` to allow interceptors to pass information down to a gruf controller

---

CHANGELOG.md
Rakefile
lib/gruf/cli/executor.rb
lib/gruf/configuration.rb
lib/gruf/controllers/health_controller.rb
script/e2e
spec/demo_server
spec/gruf/cli/executor_spec.rb
spec/gruf/controllers/health_controller_spec.rb

Adds the ability to serve the default gRPC health check class as a gruf controller automatically. This can be triggered via:
- ENV `GRUF_HEALTH_CHECK_ENABLED=1`
- `Gruf.health_check_enabled = true` in configuration
- `--health-check` CLI argument
Note that all of these default to **off** by default to prevent any regressions on upgrades for apps that may already be serving a health check.
This will bind a `Gruf::Controllers::HealthController` to the running process automatically. The health controller's `check` method will simply return a `SERVING` `::Grpc::Health::V1::HealthCheckResponse` response object.
Secondly, this PR adds a `Gruf.health_check_hook` option, that can be used to provide a custom health check response:
```ruby
Gruf.health_check_hook = lambda do |_request, _error| …
```

Add ability to serve default grpc health check

---

CHANGELOG.md
lib/gruf/controllers/autoloader.rb
spec/gruf/controllers/autoloader_spec.rb

I started getting the following error:
```
[GRPC] app err:#<GRPC::ActiveCall:0x000000011501e260>, status:13:please, finish your configuration and call Zeitwerk::Loader#setup once all is ready
```
When Zeitwerk does a `reload` ([here](https://github.com/fxn/zeitwerk/blob/4d88e4ffeef65bdedc5077deae59e729b25a6c34/lib/zeitwerk/loader.rb#L219-L227)), it "un-setups" (`#unload`) itself before a rebuild of itself (`#setup`). But it's not thread-safe so if two threads get in there, if the second one hits reload before the first has finished to re-setup. Then it's going to detect that setup hasn't run and throw the ` finish your configuration and call Zeitwerk::Loader#setup` error.
I think i started getting this after the following gem udpate(?):
```
google-protobuf (3.21.9)
grpc (1.50.0) …
```

fix a code reload  concurency issue

---

spec/gruf/interceptors/active_record/connection_reset_spec.rb
spec/gruf/interceptors/authentication/basic_spec.rb
spec/gruf/interceptors/context_spec.rb
spec/gruf/interceptors/instrumentation/output_metadata_timer_spec.rb
spec/gruf/interceptors/instrumentation/request_logging/formatters/base_spec.rb
spec/gruf/interceptors/instrumentation/request_logging/formatters/logstash_spec.rb
spec/gruf/interceptors/instrumentation/request_logging/formatters/plain_spec.rb
spec/gruf/interceptors/instrumentation/request_logging/interceptor_spec.rb
spec/gruf/interceptors/instrumentation/statsd_spec.rb
spec/gruf/interceptors/registry_spec.rb
spec/gruf/interceptors/server_interceptor_spec.rb

Fixes tests so rubocop cop `RSpec/FactoryBot/ConsistentParenthesesStyle` passes in main.
`bundle exec rubocop -P`

Fix RSpec/FactoryBot/ConsistentParenthesesStyle cop in tests

---

lib/gruf/controllers/autoloader.rb

Just some code style tidying in the autoloader to make Rubocop happy.
`bundle exec rubocop -P`

Fix Style/GuardClause cop in autoloader

---

.rubocop.yml
spec/gruf/logging_spec.rb

* Various fixes for latest rubocop so test suites pass
* Ignore `Style/RedundantConstantBase` as we prefer prefixing to allow safety in refactoring
rspec, this PR

Various fixes for latest rubocop

---

CHANGELOG.md
lib/gruf/interceptors/active_record/connection_reset.rb
spec/gruf/interceptors/active_record/connection_reset_spec.rb

- This PR support multiple databases connection reset
- In our company, we use multiple databases like below.
```yaml
production:
primary:
database: my_primary_database
username: root
password: <%= ENV['ROOT_PASSWORD'] %>
adapter: mysql2
animals:
database: my_animals_database
username: animals_root
password: <%= ENV['ANIMALS_ROOT_PASSWORD'] %>
adapter: mysql2
migrations_paths: db/animals_migrate
```
```ruby
class AnimalsRecord < ApplicationRecord
self.abstract_class = true
connects_to database: { writing: :animals }
end
```
(Copied from https://guides.rubyonrails.org/active_record_multiple_databases.html)
We use basic `Gruf::Interceptors::ActiveRecord::ConnectionReset` but there was connection pool error. After some debug, we discovered that it was a problem about our non-primary …

Support multiple databases connection reset

---

CHANGELOG.md
lib/gruf/controllers/autoloader.rb
lib/gruf/controllers/base.rb
lib/gruf/controllers/service_binder.rb
spec/gruf/controllers/autoloader_spec.rb
spec/gruf/controllers/base_spec.rb
spec/gruf/functional/server_spec.rb

- Fixes https://github.com/bigcommerce/gruf/issues/174 (at least, for us)
- Zeitwerk suggests [using a read-write lock for code reloading](https://github.com/fxn/zeitwerk#thread-safety), so that reloading cannot happen during a parallel request. 
- Moved code reloading to happen _before_ the controller is constantized, because otherwise you get a stale class and it doesn't work with reloading included modules.
- Or, rather, now it _wraps_ the entire service method call, first reloads the code if necessary, then locks for read access
- In production mode the write lock will never be acquired, and the read lock will simply let code through.
- Added tests, plus errors described in #174 went away on my machine.

Introduce read-write lock for code reloading; do code reloading before controller name resolution

---

.circleci/config.yml
gruf.gemspec

(This is an updated version of #179) Adds Ruby 3.2 support, updates CCI suite, and README.
FWIW - I tested this with a YJIT-enabled Ruby, and `RUBYOPT='--enable-yjit'` set, and the e2e suite worked as expected.
As grpc does not yet support arm macs, you'll need to run `bundle config build.grpc --with-ldflags="-Wl,-undefined,dynamic_lookup"` before bundle installing. This will be added to the wiki when this is merged.

Add Ruby 3.2 support

---

CHANGELOG.md
lib/gruf/configuration.rb

- I want to disable default interceptors 
- But `use_default_interceptors`'s default value is `true` so there are always default interceptor after `Configuration#reset` is called.
- To fix that behavior, add `GRUF_USE_DEFAULT_INTERCEPTORS` ENV to dynamically enable/disable default interceptors
- From local fork 😄

Dynamically determine use_default_interceptors

---

spec/gruf/error_spec.rb
spec/gruf/functional/interception_spec.rb
spec/gruf/functional/server_spec.rb
spec/gruf/interceptors/server_interceptor_spec.rb
spec/gruf/synchronized_client_spec.rb
spec/spec_helper.rb

This fixes `RSpec/MetadataStyle` violations by auto-correct. 
Ref: https://app.circleci.com/pipelines/github/bigcommerce/gruf/281/workflows/c3ea9b12-7d82-4ff4-814f-ab593b629bb8/jobs/3296?invite=true#step-106-117_74
The `MetadataStyle` has been added by 2.24.0. 
https://github.com/rubocop/rubocop-rspec/blob/master/CHANGELOG.md#2241-2023-09-23

Fix Rubocop violations

---

README.md

Because this gem hasn't supported Ruby 2.6 since #165.
Document change only.

Fix supported Ruby version

---

CHANGELOG.md
lib/gruf/client.rb
spec/gruf/client_spec.rb

Fixes #191. This allows passing the request object directly without first converting it to a hash.
Unit tests.

#191. Allow passing of request object directly

---

gruf.gemspec

`https://github.com/bigcommerce/gruf/CHANGELOG.md` goes to the 404 page. This PR fixes to the correct link.
None

Fix broken `changelog_uri` link

---

.circleci/config.yml
.rubocop.yml
CHANGELOG.md
README.md
gruf.gemspec
lib/gruf/configuration.rb
lib/gruf/error.rb
spec/spec_helper.rb

* Adds end-to-end Ruby 3.3 support. Local testing and the end-to-end suite in this repository was performed to ensure performance and grpc gem compatibility. All looks good.
* Drops support for Ruby 2.x, as that reached EOL in Mar 2023.
Unfortunately, grpc still is required to be compiled from source during `bundle install`, which will cause CI suites to timeout. This means this PR is effectively blocked until https://github.com/grpc/grpc/pull/35399 and https://github.com/grpc/grpc/commit/43d2b28e02174d09a64682ef0e65d7dc754f53af is released, and the grpc gem is cross-compiled and bundled.
rspec, local performance testing.

Add ruby 3.3 support, drop Ruby 2.x support

---

CHANGELOG.md
Gemfile
gruf.gemspec

It seems that unsued gems are defined in `runtime_dependency`. This PR did the following.
* Remove `thwait` from `runtime_dependency` which is only used in tests.
```bash
$ git grep thwait
Gemfile:gem 'thwait', '>= 0.1'
spec/gruf/synchronized_client_spec.rb:require 'thwait'
```
* Remove `e2mmap` from `runtime_dependency`. This gem was added by f157736,  but it seems isn't used now.
I confirmed that the specs are passed.

Fix runtime dependencies

---

CHANGELOG.md
lib/gruf/configuration.rb
lib/gruf/interceptors/rails/reloader.rb

Currently only controller code gets reloaded when using rails.
Code reload has worked well for me using this patch. Both controllers and other rails code get reloaded well.

add a code reload interceptor for rails

---

CHANGELOG.md
lib/gruf/interceptors/active_record/connection_reset.rb
spec/gruf/interceptors/active_record/connection_reset_spec.rb

Removes manual `establish_connection` from the interceptor. It seems like it was added [here](https://github.com/bigcommerce/gruf/pull/31) to support Rails 5.
* This should occur automatically if/when during the request processing in the grpc service, ActiveRecord is used to perform a query.
* For when sql server is unavailable. By checking `connection.active?` for each request and subsequently attempting to `establish_connection`, we are currently raising an exception (`Can't connect to MySQL server` etc.) in the interceptor before we can execute the `Check` inside health check endpoints. That seems incorrect.
It has been tested against 3 rails versions `[6.1, 7.0, 7.1]` using [gruf-demo repo](https://github.com/bc-amit/gruf-demo/tree/manual_establish_connection_handling_removal). In all …

Removes manual establish_connection in interceptor

---

.rubocop.yml
lib/gruf/client.rb
lib/gruf/configuration.rb
lib/gruf/hooks/registry.rb
lib/gruf/interceptors/registry.rb
spec/gruf/interceptors/instrumentation/statsd_spec.rb

In certain non-rails environments that utilize Active* gems, `Rails` may be defined, but not initialized yet, and `Rails.application` will return `nil`. This adjusts the behavior of the default interceptor loading to more defensively check for this case. In those situations, the client can decide when is the appropriate time to load the reloader interceptor.
Also fixes some rubocop errors.
E2E suite passes as expected, and tests in a local service show the app booting as expected now post fix:
```
{"message":"[gruf] Starting gruf server at 0.0.0.0:9321...","@timestamp":"2025-06-25T15:05:24.160-05:00","@version":"1","severity":"INFO","thread_id":3976}
```

Add fix for load order issues with reloader in some non-Rails environments
